// CheckStyle: stop header check
// GENERATED CONTENT - DO NOT EDIT
// Source: GraalOptions.java
package com.oracle.graal.compiler.common;

import java.util.*;
import com.oracle.graal.options.*;

public class GraalOptions_Options implements Options {
    @Override
    public Iterator<OptionDescriptor> iterator() {
        // CheckStyle: stop line length check
        List<OptionDescriptor> options = Arrays.asList(
            new OptionDescriptor("AlwaysInlineVTableStubs", Boolean.class, "", GraalOptions.class, "AlwaysInlineVTableStubs", GraalOptions.AlwaysInlineVTableStubs),
            new OptionDescriptor("BootstrapReplacements", Boolean.class, "", GraalOptions.class, "BootstrapReplacements", GraalOptions.BootstrapReplacements),
            new OptionDescriptor("CacheGraphs", Boolean.class, "", GraalOptions.class, "CacheGraphs", GraalOptions.CacheGraphs),
            new OptionDescriptor("CallArrayCopy", Boolean.class, "", GraalOptions.class, "CallArrayCopy", GraalOptions.CallArrayCopy),
            new OptionDescriptor("CanOmitFrame", Boolean.class, "", GraalOptions.class, "CanOmitFrame", GraalOptions.CanOmitFrame),
            new OptionDescriptor("ConditionalElimination", Boolean.class, "", GraalOptions.class, "ConditionalElimination", GraalOptions.ConditionalElimination),
            new OptionDescriptor("DeoptALot", Boolean.class, "", GraalOptions.class, "DeoptALot", GraalOptions.DeoptALot),
            new OptionDescriptor("DeoptsToDisableOptimisticOptimization", Integer.class, "", GraalOptions.class, "DeoptsToDisableOptimisticOptimization", GraalOptions.DeoptsToDisableOptimisticOptimization),
            new OptionDescriptor("DetailedAsserts", Boolean.class, "Enable expensive assertions", GraalOptions.class, "DetailedAsserts", GraalOptions.DetailedAsserts),
            new OptionDescriptor("DumpDuringGraphBuilding", Boolean.class, "", GraalOptions.class, "DumpDuringGraphBuilding", GraalOptions.DumpDuringGraphBuilding),
            new OptionDescriptor("EscapeAnalysisIterations", Integer.class, "", GraalOptions.class, "EscapeAnalysisIterations", GraalOptions.EscapeAnalysisIterations),
            new OptionDescriptor("EscapeAnalyzeOnly", String.class, "", GraalOptions.class, "EscapeAnalyzeOnly", GraalOptions.EscapeAnalyzeOnly),
            new OptionDescriptor("ExitVMOnBailout", Boolean.class, "", GraalOptions.class, "ExitVMOnBailout", GraalOptions.ExitVMOnBailout),
            new OptionDescriptor("ExitVMOnException", Boolean.class, "", GraalOptions.class, "ExitVMOnException", GraalOptions.ExitVMOnException),
            new OptionDescriptor("FailedLoopExplosionIsFatal", Boolean.class, "Do not bail out but throw an exception on failed loop explosion.", GraalOptions.class, "FailedLoopExplosionIsFatal", GraalOptions.FailedLoopExplosionIsFatal),
            new OptionDescriptor("FullUnroll", Boolean.class, "", GraalOptions.class, "FullUnroll", GraalOptions.FullUnroll),
            new OptionDescriptor("GCDebugStartCycle", Integer.class, "", GraalOptions.class, "GCDebugStartCycle", GraalOptions.GCDebugStartCycle),
            new OptionDescriptor("GenLoopSafepoints", Boolean.class, "", GraalOptions.class, "GenLoopSafepoints", GraalOptions.GenLoopSafepoints),
            new OptionDescriptor("GenSafepoints", Boolean.class, "", GraalOptions.class, "GenSafepoints", GraalOptions.GenSafepoints),
            new OptionDescriptor("GeneratePIC", Boolean.class, "Generate position independent code", GraalOptions.class, "GeneratePIC", GraalOptions.GeneratePIC),
            new OptionDescriptor("HotSpotPrintInlining", Boolean.class, "Print inlining optimizations", GraalOptions.class, "HotSpotPrintInlining", GraalOptions.HotSpotPrintInlining),
            new OptionDescriptor("ImmutableCode", Boolean.class, "Try to avoid emitting code where patching is required", GraalOptions.class, "ImmutableCode", GraalOptions.ImmutableCode),
            new OptionDescriptor("ImplicitStableValues", Boolean.class, "Mark well-known stable fields as such.", GraalOptions.class, "ImplicitStableValues", GraalOptions.ImplicitStableValues),
            new OptionDescriptor("InlineDuringParsing", Boolean.class, "Inlines trivial methods during parsing of the bytecodes.", GraalOptions.class, "InlineDuringParsing", GraalOptions.InlineDuringParsing),
            new OptionDescriptor("InlineDuringParsingMaxDepth", Integer.class, "Maximum depth when inlining during parsing.", GraalOptions.class, "InlineDuringParsingMaxDepth", GraalOptions.InlineDuringParsingMaxDepth),
            new OptionDescriptor("InlineEverything", Boolean.class, "", GraalOptions.class, "InlineEverything", GraalOptions.InlineEverything),
            new OptionDescriptor("InlineMegamorphicCalls", Boolean.class, "Inline calls with megamorphic type profile (i.e., not all types could be recorded).", GraalOptions.class, "InlineMegamorphicCalls", GraalOptions.InlineMegamorphicCalls),
            new OptionDescriptor("InlineMonomorphicCalls", Boolean.class, "Inline calls with monomorphic type profile.", GraalOptions.class, "InlineMonomorphicCalls", GraalOptions.InlineMonomorphicCalls),
            new OptionDescriptor("InlinePolymorphicCalls", Boolean.class, "Inline calls with polymorphic type profile.", GraalOptions.class, "InlinePolymorphicCalls", GraalOptions.InlinePolymorphicCalls),
            new OptionDescriptor("InlineVTableStubs", Boolean.class, "", GraalOptions.class, "InlineVTableStubs", GraalOptions.InlineVTableStubs),
            new OptionDescriptor("Intrinsify", Boolean.class, "Use compiler intrinsifications.", GraalOptions.class, "Intrinsify", GraalOptions.Intrinsify),
            new OptionDescriptor("IterativeInlining", Boolean.class, "", GraalOptions.class, "IterativeInlining", GraalOptions.IterativeInlining),
            new OptionDescriptor("LimitInlinedInvokes", Double.class, "", GraalOptions.class, "LimitInlinedInvokes", GraalOptions.LimitInlinedInvokes),
            new OptionDescriptor("LoopMaxUnswitch", Integer.class, "", GraalOptions.class, "LoopMaxUnswitch", GraalOptions.LoopMaxUnswitch),
            new OptionDescriptor("LoopPeeling", Boolean.class, "", GraalOptions.class, "LoopPeeling", GraalOptions.LoopPeeling),
            new OptionDescriptor("LoopUnswitch", Boolean.class, "", GraalOptions.class, "LoopUnswitch", GraalOptions.LoopUnswitch),
            new OptionDescriptor("MatchExpressions", Boolean.class, "Allow backend to match complex expressions.", GraalOptions.class, "MatchExpressions", GraalOptions.MatchExpressions),
            new OptionDescriptor("MaximumDesiredSize", Integer.class, "Maximum desired size of the compiler graph in nodes.", GraalOptions.class, "MaximumDesiredSize", GraalOptions.MaximumDesiredSize),
            new OptionDescriptor("MaximumEscapeAnalysisArrayLength", Integer.class, "", GraalOptions.class, "MaximumEscapeAnalysisArrayLength", GraalOptions.MaximumEscapeAnalysisArrayLength),
            new OptionDescriptor("MaximumInliningSize", Integer.class, "Inlining is explored up to this number of nodes in the graph for each call site.", GraalOptions.class, "MaximumInliningSize", GraalOptions.MaximumInliningSize),
            new OptionDescriptor("MaximumLoopExplosionCount", Integer.class, "Max number of loop explosions per method.", GraalOptions.class, "MaximumLoopExplosionCount", GraalOptions.MaximumLoopExplosionCount),
            new OptionDescriptor("MaximumRecursiveInlining", Integer.class, "Maximum level of recursive inlining.", GraalOptions.class, "MaximumRecursiveInlining", GraalOptions.MaximumRecursiveInlining),
            new OptionDescriptor("MegamorphicInliningMinMethodProbability", Double.class, "Minimum probability for methods to be inlined for megamorphic type profiles.", GraalOptions.class, "MegamorphicInliningMinMethodProbability", GraalOptions.MegamorphicInliningMinMethodProbability),
            new OptionDescriptor("MinimumPeelProbability", Float.class, "", GraalOptions.class, "MinimumPeelProbability", GraalOptions.MinimumPeelProbability),
            new OptionDescriptor("OmitHotExceptionStacktrace", Boolean.class, "", GraalOptions.class, "OmitHotExceptionStacktrace", GraalOptions.OmitHotExceptionStacktrace),
            new OptionDescriptor("OptAssumptions", Boolean.class, "", GraalOptions.class, "OptAssumptions", GraalOptions.OptAssumptions),
            new OptionDescriptor("OptCanonicalizer", Boolean.class, "", GraalOptions.class, "OptCanonicalizer", GraalOptions.OptCanonicalizer),
            new OptionDescriptor("OptConvertDeoptsToGuards", Boolean.class, "", GraalOptions.class, "OptConvertDeoptsToGuards", GraalOptions.OptConvertDeoptsToGuards),
            new OptionDescriptor("OptDeoptimizationGrouping", Boolean.class, "", GraalOptions.class, "OptDeoptimizationGrouping", GraalOptions.OptDeoptimizationGrouping),
            new OptionDescriptor("OptDevirtualizeInvokesOptimistically", Boolean.class, "", GraalOptions.class, "OptDevirtualizeInvokesOptimistically", GraalOptions.OptDevirtualizeInvokesOptimistically),
            new OptionDescriptor("OptEliminateGuards", Boolean.class, "", GraalOptions.class, "OptEliminateGuards", GraalOptions.OptEliminateGuards),
            new OptionDescriptor("OptEliminatePartiallyRedundantGuards", Boolean.class, "", GraalOptions.class, "OptEliminatePartiallyRedundantGuards", GraalOptions.OptEliminatePartiallyRedundantGuards),
            new OptionDescriptor("OptFilterProfiledTypes", Boolean.class, "", GraalOptions.class, "OptFilterProfiledTypes", GraalOptions.OptFilterProfiledTypes),
            new OptionDescriptor("OptFloatingReads", Boolean.class, "", GraalOptions.class, "OptFloatingReads", GraalOptions.OptFloatingReads),
            new OptionDescriptor("OptImplicitNullChecks", Boolean.class, "", GraalOptions.class, "OptImplicitNullChecks", GraalOptions.OptImplicitNullChecks),
            new OptionDescriptor("OptLivenessAnalysis", Boolean.class, "", GraalOptions.class, "OptLivenessAnalysis", GraalOptions.OptLivenessAnalysis),
            new OptionDescriptor("OptLoopTransform", Boolean.class, "", GraalOptions.class, "OptLoopTransform", GraalOptions.OptLoopTransform),
            new OptionDescriptor("OptPushThroughPi", Boolean.class, "", GraalOptions.class, "OptPushThroughPi", GraalOptions.OptPushThroughPi),
            new OptionDescriptor("OptReadElimination", Boolean.class, "", GraalOptions.class, "OptReadElimination", GraalOptions.OptReadElimination),
            new OptionDescriptor("OptScheduleOutOfLoops", Boolean.class, "", GraalOptions.class, "OptScheduleOutOfLoops", GraalOptions.OptScheduleOutOfLoops),
            new OptionDescriptor("OptTailDuplication", Boolean.class, "", GraalOptions.class, "OptTailDuplication", GraalOptions.OptTailDuplication),
            new OptionDescriptor("PEAInliningHints", Boolean.class, "", GraalOptions.class, "PEAInliningHints", GraalOptions.PEAInliningHints),
            new OptionDescriptor("PartialEscapeAnalysis", Boolean.class, "", GraalOptions.class, "PartialEscapeAnalysis", GraalOptions.PartialEscapeAnalysis),
            new OptionDescriptor("PrintAfterCompilation", Boolean.class, "", GraalOptions.class, "PrintAfterCompilation", GraalOptions.PrintAfterCompilation),
            new OptionDescriptor("PrintBackendCFG", Boolean.class, "Enable dumping LIR, register allocation and code generation info to the C1Visualizer.", GraalOptions.class, "PrintBackendCFG", GraalOptions.PrintBackendCFG),
            new OptionDescriptor("PrintBailout", Boolean.class, "", GraalOptions.class, "PrintBailout", GraalOptions.PrintBailout),
            new OptionDescriptor("PrintBinaryGraphPort", Integer.class, "", GraalOptions.class, "PrintBinaryGraphPort", GraalOptions.PrintBinaryGraphPort),
            new OptionDescriptor("PrintBinaryGraphs", Boolean.class, "Dump IdealGraphVisualizer output in binary format", GraalOptions.class, "PrintBinaryGraphs", GraalOptions.PrintBinaryGraphs),
            new OptionDescriptor("PrintCFG", Boolean.class, "Enable dumping to the C1Visualizer. Enabling this option implies PrintBackendCFG.", GraalOptions.class, "PrintCFG", GraalOptions.PrintCFG),
            new OptionDescriptor("PrintCodeBytes", Boolean.class, "", GraalOptions.class, "PrintCodeBytes", GraalOptions.PrintCodeBytes),
            new OptionDescriptor("PrintCompilation", Boolean.class, "", GraalOptions.class, "PrintCompilation", GraalOptions.PrintCompilation),
            new OptionDescriptor("PrintFilter", String.class, "", GraalOptions.class, "PrintFilter", GraalOptions.PrintFilter),
            new OptionDescriptor("PrintGraphProbabilities", Boolean.class, "Output probabilities for fixed nodes during binary graph dumping", GraalOptions.class, "PrintGraphProbabilities", GraalOptions.PrintGraphProbabilities),
            new OptionDescriptor("PrintIdealGraph", Boolean.class, "Enable dumping to the IdealGraphVisualizer.", GraalOptions.class, "PrintIdealGraph", GraalOptions.PrintIdealGraph),
            new OptionDescriptor("PrintIdealGraphAddress", String.class, "", GraalOptions.class, "PrintIdealGraphAddress", GraalOptions.PrintIdealGraphAddress),
            new OptionDescriptor("PrintIdealGraphFile", Boolean.class, "", GraalOptions.class, "PrintIdealGraphFile", GraalOptions.PrintIdealGraphFile),
            new OptionDescriptor("PrintIdealGraphPort", Integer.class, "", GraalOptions.class, "PrintIdealGraphPort", GraalOptions.PrintIdealGraphPort),
            new OptionDescriptor("PrintIdealGraphSchedule", Boolean.class, "", GraalOptions.class, "PrintIdealGraphSchedule", GraalOptions.PrintIdealGraphSchedule),
            new OptionDescriptor("PrintProfilingInformation", Boolean.class, "Print profiling information when parsing a method's bytecode", GraalOptions.class, "PrintProfilingInformation", GraalOptions.PrintProfilingInformation),
            new OptionDescriptor("PrintStackTraceOnException", Boolean.class, "", GraalOptions.class, "PrintStackTraceOnException", GraalOptions.PrintStackTraceOnException),
            new OptionDescriptor("ReassociateInvariants", Boolean.class, "", GraalOptions.class, "ReassociateInvariants", GraalOptions.ReassociateInvariants),
            new OptionDescriptor("RegisterPressure", String.class, "Comma separated list of register that the allocation is limited to.", GraalOptions.class, "RegisterPressure", GraalOptions.RegisterPressure),
            new OptionDescriptor("RemoveNeverExecutedCode", Boolean.class, "", GraalOptions.class, "RemoveNeverExecutedCode", GraalOptions.RemoveNeverExecutedCode),
            new OptionDescriptor("ResolveClassBeforeStaticInvoke", Boolean.class, "", GraalOptions.class, "ResolveClassBeforeStaticInvoke", GraalOptions.ResolveClassBeforeStaticInvoke),
            new OptionDescriptor("SmallCompiledLowLevelGraphSize", Integer.class, "If the previous low-level graph size of the method exceeds the threshold, it is not inlined.", GraalOptions.class, "SmallCompiledLowLevelGraphSize", GraalOptions.SmallCompiledLowLevelGraphSize),
            new OptionDescriptor("SnippetCounters", Boolean.class, "", GraalOptions.class, "SnippetCounters", GraalOptions.SnippetCounters),
            new OptionDescriptor("StressExplicitExceptionCode", Boolean.class, "Stressed the code emitting explicit exception throwing code.", GraalOptions.class, "StressExplicitExceptionCode", GraalOptions.StressExplicitExceptionCode),
            new OptionDescriptor("SupportJsrBytecodes", Boolean.class, "", GraalOptions.class, "SupportJsrBytecodes", GraalOptions.SupportJsrBytecodes),
            new OptionDescriptor("TailDuplicationProbability", Double.class, "", GraalOptions.class, "TailDuplicationProbability", GraalOptions.TailDuplicationProbability),
            new OptionDescriptor("TailDuplicationTrivialSize", Integer.class, "", GraalOptions.class, "TailDuplicationTrivialSize", GraalOptions.TailDuplicationTrivialSize),
            new OptionDescriptor("TraceEscapeAnalysis", Boolean.class, "", GraalOptions.class, "TraceEscapeAnalysis", GraalOptions.TraceEscapeAnalysis),
            new OptionDescriptor("TraceInlineDuringParsing", Boolean.class, "Traces .", GraalOptions.class, "TraceInlineDuringParsing", GraalOptions.TraceInlineDuringParsing),
            new OptionDescriptor("TrivialInliningSize", Integer.class, "Graphs with less than this number of nodes are trivial and therefore always inlined.", GraalOptions.class, "TrivialInliningSize", GraalOptions.TrivialInliningSize),
            new OptionDescriptor("TrustFinalDefaultFields", Boolean.class, "Constant fold final fields with default values.", GraalOptions.class, "TrustFinalDefaultFields", GraalOptions.TrustFinalDefaultFields),
            new OptionDescriptor("UseExceptionProbability", Boolean.class, "", GraalOptions.class, "UseExceptionProbability", GraalOptions.UseExceptionProbability),
            new OptionDescriptor("UseExceptionProbabilityForOperations", Boolean.class, "", GraalOptions.class, "UseExceptionProbabilityForOperations", GraalOptions.UseExceptionProbabilityForOperations),
            new OptionDescriptor("UseLoopLimitChecks", Boolean.class, "", GraalOptions.class, "UseLoopLimitChecks", GraalOptions.UseLoopLimitChecks),
            new OptionDescriptor("UseProfilingInformation", Boolean.class, "", GraalOptions.class, "UseProfilingInformation", GraalOptions.UseProfilingInformation),
            new OptionDescriptor("UseTypeCheckHints", Boolean.class, "", GraalOptions.class, "UseTypeCheckHints", GraalOptions.UseTypeCheckHints),
            new OptionDescriptor("VerifyHeapAtReturn", Boolean.class, "Perform platform dependent validation of the Java heap at returns", GraalOptions.class, "VerifyHeapAtReturn", GraalOptions.VerifyHeapAtReturn),
            new OptionDescriptor("VerifyPhases", Boolean.class, "", GraalOptions.class, "VerifyPhases", GraalOptions.VerifyPhases),
            new OptionDescriptor("ZapStackOnMethodEntry", Boolean.class, "", GraalOptions.class, "ZapStackOnMethodEntry", GraalOptions.ZapStackOnMethodEntry)
        );
        // CheckStyle: resume line length check
        return options.iterator();
    }
}
